"""ff

Revision ID: 06a89e457c6f
Revises: e36c6dd5d8fd
Create Date: 2023-06-25 23:29:21.239815

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "06a89e457c6f"
down_revision = "e36c6dd5d8fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shot", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("player_shot_team_year_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "test", "player_shot_team_year", ["player_shot_team_year_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shot", schema=None) as batch_op:
        batch_op.drop_constraint("test", type_="foreignkey")
        batch_op.drop_column("player_shot_team_year_id")

    # ### end Alembic commands ###
