"""Add group id foreign key to shot

Revision ID: 2e52b67b663c
Revises: 9fa4dd909d47
Create Date: 2023-07-05 20:51:35.163456

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "2e52b67b663c"
down_revision = "9fa4dd909d47"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shot", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "lineup_group_id", "lineup", ["GROUP_ID"], ["GROUP_ID"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shot", schema=None) as batch_op:
        batch_op.drop_constraint("lineup_group_id", type_="foreignkey")

    # ### end Alembic commands ###
