"""Add relationship between player and lineup

Revision ID: 457b32c2837c
Revises: 4f670dc8bfc8
Create Date: 2023-07-05 15:33:47.239392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457b32c2837c'
down_revision = '4f670dc8bfc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineup_player_association',
    sa.Column('lineup_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lineup_id'], ['lineup.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.PLAYER_ID'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineup_player_association')
    # ### end Alembic commands ###
