"""Make player_id required

Revision ID: 4752c62dfb46
Revises: 0285fff11139
Create Date: 2023-06-30 11:54:32.911094

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4752c62dfb46"
down_revision = "0285fff11139"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.alter_column("PLAYER_ID", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.alter_column("PLAYER_ID", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
