"""Add lineup model

Revision ID: 4f670dc8bfc8
Revises: f691fe29cf46
Create Date: 2023-07-05 14:15:30.077898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f670dc8bfc8'
down_revision = 'f691fe29cf46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lineup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('GROUP_ID', sa.String(length=100), nullable=False),
    sa.Column('GROUP_NAME', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineup')
    # ### end Alembic commands ###
