"""Change season_year to string in PlayerShotTeamYear

Revision ID: 8be4760c2722
Revises: 68dcc1f0f14b
Create Date: 2023-06-27 01:42:06.215232

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8be4760c2722"
down_revision = "68dcc1f0f14b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_shot_team_year", schema=None) as batch_op:
        batch_op.alter_column(
            "season_year",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=255),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_shot_team_year", schema=None) as batch_op:
        batch_op.alter_column(
            "season_year",
            existing_type=sa.String(length=255),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
