"""Add empty to PlayerShotTeamYear

Revision ID: a350765c790e
Revises: 8be4760c2722
Create Date: 2023-06-27 13:17:53.276756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a350765c790e'
down_revision = '8be4760c2722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_shot_team_year', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empty', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_shot_team_year', schema=None) as batch_op:
        batch_op.drop_column('empty')

    # ### end Alembic commands ###
