"""Add Game

Revision ID: ab5a81292fd7
Revises: 4752c62dfb46
Create Date: 2023-06-30 17:50:56.569640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5a81292fd7'
down_revision = '4752c62dfb46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('GAME_ID', sa.Integer(), nullable=False),
    sa.Column('HTM', sa.String(length=100), nullable=True),
    sa.Column('VTM', sa.String(length=100), nullable=True),
    sa.Column('GAME_DATE', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_shot_team_year', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_player_shot_team_year_player_shot_career_id", 'player_shot_career', ['player_shot_career_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_shot_team_year', schema=None) as batch_op:
        batch_op.drop_constraint("fk_player_shot_team_year_player_shot_career_id", type_='foreignkey')

    op.drop_table('game')
    # ### end Alembic commands ###
