"""Add more indexes

Revision ID: aefa6033c860
Revises: c00a6c1668a9
Create Date: 2023-07-06 11:45:55.396701

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "aefa6033c860"
down_revision = "c00a6c1668a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shot", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shot_GAME_ID"), ["GAME_ID"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_shot_season_year"), ["season_year"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shot", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shot_season_year"))
        batch_op.drop_index(batch_op.f("ix_shot_GAME_ID"))

    # ### end Alembic commands ###
