"""Make group_id required

Revision ID: bf2f91b4a34d
Revises: 457b32c2837c
Create Date: 2023-07-05 15:41:07.513852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2f91b4a34d'
down_revision = '457b32c2837c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lineup', schema=None) as batch_op:
        batch_op.create_unique_constraint('group_id_uniq', ['GROUP_ID'])
        batch_op.create_unique_constraint('group_name_uniq', ['GROUP_NAME'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lineup', schema=None) as batch_op:
        batch_op.drop_constraint('group_id_uniq', type_='unique')
        batch_op.drop_constraint('group_name_uniq', type_='unique')

    # ### end Alembic commands ###
