"""Update column names in Shot

Revision ID: eb75375fa54d
Revises: a350765c790e
Create Date: 2023-06-27 13:42:47.640260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb75375fa54d'
down_revision = 'a350765c790e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shot', schema=None) as batch_op:
        batch_op.alter_column('grid_type', new_column_name='GRID_TYPE')
        batch_op.alter_column('game_id', new_column_name='GAME_ID')
        batch_op.alter_column('game_event_id', new_column_name='GAME_EVENT_ID')
        batch_op.alter_column('player_id', new_column_name='PLAYER_ID', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('player_name', new_column_name='PLAYER_NAME')
        batch_op.alter_column('team_id', new_column_name='TEAM_ID')
        batch_op.alter_column('team_name', new_column_name='TEAM_NAME')
        batch_op.alter_column('period', new_column_name='PERIOD')
        batch_op.alter_column('minutes_remaining', new_column_name='MINUTES_REMAINING')
        batch_op.alter_column('seconds_remaining', new_column_name='SECONDS_REMAINING')
        batch_op.alter_column('event_type', new_column_name='EVENT_TYPE')
        batch_op.alter_column('action_type', new_column_name='ACTION_TYPE')
        batch_op.alter_column('shot_type', new_column_name='SHOT_TYPE')
        batch_op.alter_column('shot_zone_basic', new_column_name='SHOT_ZONE_BASIC')
        batch_op.alter_column('shot_zone_area', new_column_name='SHOT_ZONE_AREA')
        batch_op.alter_column('shot_zone_range', new_column_name='SHOT_ZONE_RANGE')
        batch_op.alter_column('shot_distance', new_column_name='SHOT_DISTANCE')
        batch_op.alter_column('loc_x', new_column_name='LOC_X')
        batch_op.alter_column('loc_y', new_column_name='LOC_Y')
        batch_op.alter_column('shot_attempted_flag', new_column_name='SHOT_ATTEMPTED_FLAG')
        batch_op.alter_column('shot_made_flag', new_column_name='SHOT_MADE_FLAG')
        batch_op.alter_column('game_date', new_column_name='GAME_DATE')
        batch_op.alter_column('htm', new_column_name='HTM')
        batch_op.alter_column('vtm', new_column_name='VTM')
        batch_op.add_column(sa.Column('season_year', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shot_value', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shot_result', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_shot_PLAYER_ID_player_id', 'player', ['PLAYER_ID'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shot', schema=None) as batch_op:
        batch_op.alter_column('GRID_TYPE', new_column_name='grid_type')
        batch_op.alter_column('GAME_ID', new_column_name='game_id')
        batch_op.alter_column('GAME_EVENT_ID', new_column_name='game_event_id')
        batch_op.alter_column('PLAYER_ID', new_column_name='player_id', existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column('PLAYER_NAME', new_column_name='player_name')
        batch_op.alter_column('TEAM_ID', new_column_name='team_id')
        batch_op.alter_column('TEAM_NAME', new_column_name='team_name')
        batch_op.alter_column('PERIOD', new_column_name='period')
        batch_op.alter_column('MINUTES_REMAINING', new_column_name='minutes_remaining')
        batch_op.alter_column('SECONDS_REMAINING', new_column_name='seconds_remaining')
        batch_op.alter_column('EVENT_TYPE', new_column_name='event_type')
        batch_op.alter_column('ACTION_TYPE', new_column_name='action_type')
        batch_op.alter_column('SHOT_TYPE', new_column_name='shot_type')
        batch_op.alter_column('SHOT_ZONE_BASIC', new_column_name='shot_zone_basic')
        batch_op.alter_column('SHOT_ZONE_AREA', new_column_name='shot_zone_area')
        batch_op.alter_column('SHOT_ZONE_RANGE', new_column_name='shot_zone_range')
        batch_op.alter_column('SHOT_DISTANCE', new_column_name='shot_distance')
        batch_op.alter_column('LOC_X', new_column_name='loc_x')
        batch_op.alter_column('LOC_Y', new_column_name='loc_y')
        batch_op.alter_column('SHOT_ATTEMPTED_FLAG', new_column_name='shot_attempted_flag')
        batch_op.alter_column('SHOT_MADE_FLAG', new_column_name='shot_made_flag')
        batch_op.alter_column('GAME_DATE', new_column_name='game_date')
        batch_op.alter_column('HTM', new_column_name='htm')
        batch_op.alter_column('VTM', new_column_name='vtm')
        batch_op.create_foreign_key('fk_shot_player_id_player_id', 'player', ['player_id'], ['id'])
        batch_op.drop_column('shot_result')
        batch_op.drop_column('shot_value')
        batch_op.drop_column('season_year')
      

    # ### end Alembic commands ###
