"""Add group_id and group_name to shot

Revision ID: f691fe29cf46
Revises: 4f8d47a421b6
Create Date: 2023-07-05 13:51:12.189685

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f691fe29cf46"
down_revision = "4f8d47a421b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shot", schema=None) as batch_op:
        batch_op.add_column(sa.Column("GROUP_ID", sa.String(length=100), nullable=True))
        batch_op.add_column(
            sa.Column("GROUP_NAME", sa.String(length=100), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shot", schema=None) as batch_op:
        batch_op.drop_column("GROUP_NAME")
        batch_op.drop_column("GROUP_ID")

    # ### end Alembic commands ###
