version: '3.8'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.backend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"