version: '3.8'
services:
  moneybasketball-api:
    build: 
      context: .
      dockerfile: Dockerfile.backend
  moneybasketball-fe:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"