name: Deploy to Cloud Storage and Cloud Run

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  setup:
    name: Setup Google Cloud
    runs-on: ubuntu-latest
    outputs:
      project_id: ${{ steps.set_vars.outputs.project_id }}
    steps:
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Fetch project ID
        id: set_vars
        run: echo "::set-output name=project_id::$(gcloud config get-value project)"

  deploy-backend:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker image to Google Container Registry
        run: |
          docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/moneybasketball/moneybasketball-api:$GITHUB_SHA -f Dockerfile.backend .
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/moneybasketball/moneybasketball-api:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy moneybasketball-api --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/moneybasketball/moneybasketball-api:$GITHUB_SHA --platform managed --region ${{ secrets.GCP_REGION }}

  deploy-frontend:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies and build the frontend
        run: |
          npm install
          npm run build
        working-directory: ./frontend/

      - name: Deploy to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v0.7.0
        with:
          path: ./frontend/build
          destination: gs://${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_GCS_BUCKET }}

